[package]
name = "verzion"
version = "0.1.0"
edition = "2024"

[dependencies]
serde_json = "1.0"
serde-xml-rs = "0.8.1"
serde = { version = "1.0", features = ["derive"] }
clap = { version = "4.5.51", features = ["derive"] }
